# Build, test, and install on different versions of MacOS
name: MacOS

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

env:
  # CMake configuration for basic build
  CMAKE_CONFIG_FLAGS: -DCMAKE_INSTALL_PREFIX=`pwd` -DCMAKE_BUILD_TYPE=Release

jobs:
  build-test-install:
    strategy: 
      matrix:
        os: [macos-11, macos-latest]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build ${{env.CMAKE_CONFIG_FLAGS}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Install
      run: cmake --install ${{github.workspace}}/build
